version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    build: ../frontend
    volumes:
      - static:/app/result_build
  gateway:
    build:
      dockerfile: infra/Dockerfile
      context: ../
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media