version: '3'

name: foodgram-project-react

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    build: ../frontend
    volumes:
      - static:/app/result_build
  gateway:
    image: nginx:1.19.3
    depends_on:
      - frontend
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs:/usr/share/nginx/html/api/docs/