version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: parhoc/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: parhoc/foodgram_frontend
    volumes:
      - static:/app/result_build
  gateway:
    image: parhoc/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
      - ../docs/:/usr/share/nginx/html/api/docs/