# Generated by Django 3.2 on 2024-02-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240116_0953'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, username__in=('me',)), name='invalid_username'),
        ),
    ]
