# Generated by Django 3.2 on 2024-02-15 09:57

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_invalid_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='invalid_username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.validate_username], verbose_name='Логин'),
        ),
    ]
